spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.cpib7pvrik8j.eu-central-1.rds.amazonaws.com:5432/amigoscodedemo
    username: lordxray
    password: sphingalama33
    pool-size: 30