server:
  servlet:
    context-path: /api
  port: 8080
  error:
    include-message: always
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/amigoscodedemo
    username: postgres
    password: sphingalama33
    pool-size: 30
logging:
  file.name: /logs/application-debug.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.howtodoinjava: INFO
    org.hibernate: INFO

